# Demo

### Eventlog Extraction

In [1]:
import polars as pl

eventlog = pl.read_csv("generated_event_log/demo_1_without_user-subagents.csv")
eventlog.shape

(367, 13)

In [2]:
eventlog.columns

['case_id',
 'identity:id',
 'time:timestamp',
 'concept:instance',
 'concept:name',
 'org:resource',
 'message',
 'time_finished',
 'duration',
 'model',
 'input_tokens',
 'response_tokens',
 'tool']

In [3]:
eventlog

shape: (367, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ case_id   ┆ identity: ┆ time:time ┆ concept:i ┆ … ┆ model     ┆ input_tok ┆ response_ ┆ tool     │
│ ---       ┆ id        ┆ stamp     ┆ nstance   ┆   ┆ ---       ┆ ens       ┆ tokens    ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ str      │
│           ┆ str       ┆ str       ┆ str       ┆   ┆           ┆ f64       ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 8e1ac142- ┆ 0b907b5f- ┆ 2026-05-0 ┆ prompt    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ da98-4bf8 ┆ 1650-4225 ┆ 5T08:47:5 ┆           ┆   ┆           ┆           ┆           ┆          │
│ -b77a-ab4 ┆ -b724-0f5 ┆ 2.239     ┆           ┆   ┆           ┆           ┆           ┆          │
│ 472…      ┆ a23…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8e1ac142- ┆ 2c49745a- ┆ 2026-05-0 ┆ order_age ┆ … ┆ ministral ┆ 689.0     ┆ 62.0      ┆ null     │
│ da98-4bf8 ┆ f0bc-4290 ┆ 5T08:47:5 ┆ nt calls  ┆   ┆ -3:14b    ┆           ┆           ┆          │
│ -b77a-ab4 ┆ -8acb-9f5 ┆ 2.249     ┆ llm       ┆   ┆           ┆           ┆           ┆          │
│ 472…      ┆ 53b…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8e1ac142- ┆ c90e4ee8- ┆ 2026-05-0 ┆ prompt    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ da98-4bf8 ┆ 418b-43fa ┆ 5T08:48:1 ┆           ┆   ┆           ┆           ┆           ┆          │
│ -b77a-ab4 ┆ -a24d-b91 ┆ 6.660     ┆           ┆   ┆           ┆           ┆           ┆          │
│ 472…      ┆ c12…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8e1ac142- ┆ dcb94e02- ┆ 2026-05-0 ┆ order_age ┆ … ┆ ministral ┆ 763.0     ┆ 35.0      ┆ null     │
│ da98-4bf8 ┆ 441c-472f ┆ 5T08:48:1 ┆ nt calls  ┆   ┆ -3:14b    ┆           ┆           ┆          │
│ -b77a-ab4 ┆ -84a8-c3e ┆ 6.669     ┆ llm       ┆   ┆           ┆           ┆           ┆          │
│ 472…      ┆ 23a…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8e1ac142- ┆ e9b01478- ┆ 2026-05-0 ┆ order_age ┆ … ┆ null      ┆ null      ┆ null      ┆ process_ │
│ da98-4bf8 ┆ 61ce-4e3b ┆ 5T08:48:3 ┆ nt uses   ┆   ┆           ┆           ┆           ┆ order    │
│ -b77a-ab4 ┆ -8d53-00e ┆ 0.921     ┆ tool      ┆   ┆           ┆           ┆           ┆          │
│ 472…      ┆ 6aa…      ┆           ┆ process_… ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ cd0dd7d4- ┆ cbbfb46b- ┆ 2026-05-0 ┆ barista_a ┆ … ┆ null      ┆ null      ┆ null      ┆ prepare_ │
│ 3967-4326 ┆ 3de6-45cb ┆ 7T10:26:0 ┆ gent uses ┆   ┆           ┆           ┆           ┆ order    │
│ -a5e5-10b ┆ -afef-416 ┆ 4.246     ┆ tool      ┆   ┆           ┆           ┆           ┆          │
│ eb9…      ┆ e14…      ┆           ┆ prepar…   ┆   ┆           ┆           ┆           ┆          │
│ cd0dd7d4- ┆ 09a0ddf9- ┆ 2026-05-0 ┆ barista_a ┆ … ┆ ministral ┆ 1662.0    ┆ 256.0     ┆ null     │
│ 3967-4326 ┆ aaed-4f11 ┆ 7T10:26:0 ┆ gent      ┆   ┆ -3:14b    ┆           ┆           ┆          │
│ -a5e5-10b ┆ -962c-a06 ┆ 4.256     ┆ calls llm ┆   ┆           ┆           ┆           ┆          │
│ eb9…      ┆ c8e…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ cd0dd7d4- ┆ b19fb4b5- ┆ 2026-05-0 ┆ prompt    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 3967-4326 ┆ 3240-466a ┆ 7T10:26:2 ┆           ┆   ┆           ┆           ┆           ┆          │
│ -a5e5-10b ┆ -be6d-0a8 ┆ 1.090     ┆           ┆   ┆           ┆           ┆           ┆          │
│ eb9…      ┆ ebb…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ cd0dd7d4- ┆ ac340260- ┆ 2026-05-0 ┆ barista_a ┆ … ┆ ministral ┆ 1924.0    ┆ 9.0       ┆ null     │
│ 3967-4326 ┆ dd5a-4446 ┆ 7T10:26:2 ┆ gent      ┆   ┆ -3:14b    ┆           ┆           ┆          │
│ -a5e5-10b ┆ -9cea-164 ┆ 1.204     ┆ calls llm ┆   ┆           ┆           ┆           ┆          │
│ eb9…      ┆ 4e5…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ cd0dd7d4- ┆ ac83cb65- ┆ 2026-05-0 ┆ customer_ ┆ … ┆ ministral ┆ 1949.0    ┆ 174.0     ┆ null     │
│ 3967-4326 ┆ d3c0-4d04 ┆ 7T10:26:3 ┆ service_a ┆   ┆ -3:14b    ┆           ┆           ┆          │
│ -a5e5-10b ┆ -8b45-5f5 ┆ 1.323     ┆ gent      ┆   ┆           ┆           ┆           ┆          │
│ eb9…      ┆ ebd…      ┆           ┆ calls l…  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Object-centric Eventlog Conversion

In [4]:
from src.eventlog_conversion import ObjectCentricEventlog

ocel = ObjectCentricEventlog.from_eventlog(eventlog)

In [7]:
ocel.export_to_json("demo_ocel")

In [5]:
ocel.objects

shape: (250, 2)
┌─────────────────────────────────┬─────────────────┐
│ ocel_id                         ┆ ocel_type       │
│ ---                             ┆ ---             │
│ str                             ┆ str             │
╞═════════════════════════════════╪═════════════════╡
│ 8f65d8ee-b570-46a2-9e1b-573cce… ┆ user            │
│ response_0ba5e0c9-444e-4654-a7… ┆ response        │
│ 7efccf29-06bc-4d72-ab86-0a739d… ┆ barista_agent   │
│ 7efccf29-06bc-4d72-ab86-0a739d… ┆ inventory_agent │
│ response_c929216f-9653-430b-b0… ┆ response        │
│ …                               ┆ …               │
│ response_911694c4-6592-4f3a-9e… ┆ response        │
│ prompt_7a1a1434-28cd-47b7-bfd7… ┆ prompt          │
│ prompt_9071c848-b29a-4df5-8d7c… ┆ prompt          │
│ response_67fd0163-0ca0-4037-b4… ┆ response        │
│ response_2fc7e790-3953-432c-95… ┆ response        │
└─────────────────────────────────┴─────────────────┘

In [6]:
ocel.object_tables["object_prompt"]

shape: (77, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ ocel_id                         ┆ message                         │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ prompt_400959ae-70d8-4d86-95d7… ┆ Ooo, the Honey Lavender sounds… │
│ prompt_5dddcf15-0fec-4ac3-a0bc… ┆ Nah, it’s perfect as is—just t… │
│ prompt_44ced5b6-4e29-4cfd-8549… ┆ "Hey! I’m new here—what’s your… │
│ prompt_5a87a3ad-bfa7-416d-a5be… ┆ I’d prefer a fresh one now if … │
│ prompt_676d2b7d-c928-4aa3-8890… ┆ Large cinnamon cappuccino + ch… │
│ …                               ┆ …                               │
│ prompt_8101d072-0256-4ace-8480… ┆ "Free drink next time is fine—… │
│ prompt_c3b08d19-795f-43f2-9c25… ┆ Sounds great—proceed!           │
│ prompt_355a356b-fddc-4f56-9356… ┆ "Hey! Can I get 2 quick espres… │
│ prompt_15946bda-4c2a-4558-b39e… ┆ Large Cinnamon Chai Latte—extr… │
│ prompt_c91e14a0-c9bf-4353-8881… ┆ Ooh, the spiced chai sounds *p… │
└─────────────────────────────────┴─────────────────────────────────┘

### Visualization

In [9]:
from src.visualization.visualizer import Visualizer, VisualizationConfig
from pathlib import Path

config = VisualizationConfig(
    ocel_path=Path("generated_ocel/demo_ocel.json"),
    out_dir=Path("generated_visualizations"),
    color_map={
        "order_agent":            "#AED6F1",  # pastel blue
        "barista_agent":          "#A9DFBF",  # pastel green
        "inventory_agent":        "#FAD7A0",  # pastel orange
        "customer_service_agent": "#D7BDE2",  # pastel purple
        "user":                   "#D5D8DC",  # pastel grey
        "prompt":                 "#A3E4D7",  # pastel teal
        "response":               "#F9E79F",  # pastel yellow
    }
)
visualizer = Visualizer(config)
outputs = visualizer.run()